"""Owned console + Codex command-runner differential; never touches daily config.

The command is read from hooks.json generated by real TabBeacon setup. Only the
CREATE_NO_WINDOW flag differs between A/B. Capture sizes, outcomes and V2 timing,
never captured protocol output or payload text. Job assignment precedes resume.
"""
import ctypes as c
from ctypes import wintypes as w
import hashlib
import json
import os
from pathlib import Path
import subprocess as sp
import sys
import shutil
import time
from concurrent.futures import ThreadPoolExecutor

k = c.WinDLL('kernel32', use_last_error=True)
k.CreateJobObjectW.restype = w.HANDLE
k.CreateJobObjectW.argtypes = [c.c_void_p, w.LPCWSTR]
k.SetInformationJobObject.argtypes = [w.HANDLE, c.c_int, c.c_void_p, w.DWORD]
k.AssignProcessToJobObject.argtypes = [w.HANDLE, w.HANDLE]
k.TerminateJobObject.argtypes = [w.HANDLE, w.UINT]
k.CloseHandle.argtypes = [w.HANDLE]
k.CreateFileW.restype = w.HANDLE
k.CreateFileW.argtypes = [w.LPCWSTR,w.DWORD,w.DWORD,c.c_void_p,w.DWORD,w.DWORD,w.HANDLE]
k.GetConsoleWindow.restype = w.HWND

class Basic(c.Structure):
    _fields_ = [('process_time',c.c_int64),('job_time',c.c_int64),('flags',w.DWORD),
                ('min_ws',c.c_size_t),('max_ws',c.c_size_t),('active_limit',w.DWORD),
                ('affinity',c.c_size_t),('priority',w.DWORD),('scheduling',w.DWORD)]
class Extended(c.Structure):
    _fields_ = [('basic',Basic),('io',c.c_uint64*6),('pmem',c.c_size_t),
                ('jmem',c.c_size_t),('peakp',c.c_size_t),('peakj',c.c_size_t)]

def inspect():
    pids = (w.DWORD*8)()
    count = k.GetConsoleProcessList(pids,8)
    attached = count>0
    h=k.CreateFileW('CONOUT$',0xC0000000,3,None,3,0,None)
    mode=w.DWORD()
    usable=h not in (None,c.c_void_p(-1).value) and bool(k.GetConsoleMode(w.HANDLE(h),c.byref(mode)))
    if h not in (None,c.c_void_p(-1).value): k.CloseHandle(h)
    return {'console_attached':attached,'conout_usable':usable,'vt_enabled':bool(mode.value&4),
            'console_member_count':count,'origin_in_console':int(os.getenv('TB_FIXTURE_ORIGIN_PID','0')) in list(pids),
            'wt_session_present':bool(os.getenv('WT_SESSION'))}

if len(sys.argv)>1 and sys.argv[1]=='--inspect':
    Path(sys.argv[2]).write_text(json.dumps(inspect()),encoding='utf-8')
    sys.exit(0)

binary=Path(sys.argv[1]).resolve()
outroot=Path(sys.argv[2]).resolve()
outroot.mkdir(exist_ok=False)
# The host can expose a synthetic console process list even with no HWND.
# Detach this fixture process only, then allocate an explicitly owned console.
if os.getenv('TB_OWNED_NATIVE_PARENT'):
    k.FreeConsole()
    if not k.AttachConsole(int(os.environ['TB_OWNED_NATIVE_PARENT'])): raise c.WinError(c.get_last_error())
else:
    k.FreeConsole()
    if not k.AllocConsole(): raise c.WinError(c.get_last_error())
    u=c.WinDLL('user32'); u.ShowWindow.argtypes=[w.HWND,c.c_int]
    u.ShowWindow(k.GetConsoleWindow(),0)
h=k.CreateFileW('CONOUT$',0xC0000000,3,None,3,0,None)
mode=w.DWORD(); k.GetConsoleMode(w.HANDLE(h),c.byref(mode))
k.SetConsoleMode(w.HANDLE(h),mode.value|4); k.CloseHandle(h)

env={name:os.environ[name] for name in ['SystemRoot','WINDIR','COMSPEC','PATH','PATHEXT','TEMP','TMP','USERPROFILE'] if name in os.environ}
env.update(LOCALAPPDATA=str(outroot/'appdata'),CODEX_HOME=str(outroot/'codex-home'),WT_SESSION='tb-v0801-fixture-owned-console',TB_FIXTURE_ORIGIN_PID=str(os.getpid()))
Path(env['CODEX_HOME']).mkdir(); Path(env['LOCALAPPDATA']).mkdir()
job=k.CreateJobObjectW(None,None)
limits=Extended(); limits.basic.flags=0x2000
if not k.SetInformationJobObject(job,9,c.byref(limits),c.sizeof(limits)): raise c.WinError(c.get_last_error())
resume=c.WinDLL('ntdll').NtResumeProcess; resume.argtypes=[w.HANDLE]; resume.restype=c.c_long
results=[]
shell=os.environ.get('TB_CONSOLE_FIXTURE_SHELL','COMSPEC')
if shell not in ('COMSPEC','Pwsh7'): raise ValueError('Unknown fixture shell')
def invocation(command):
    if shell=='Pwsh7':
        pwsh=shutil.which('pwsh.exe')
        if not pwsh: raise RuntimeError('Pwsh7 unavailable')
        # Official shell::derive_exec_args(command, false), no extra flags.
        return [pwsh,'-NoProfile','-Command',command]
    return f'"{env.get("COMSPEC","cmd.exe")}" /C "{command}"'

def run(command,flags,payload=None,deadline=1):
    start=time.perf_counter()
    process=sp.Popen(command,env=env,cwd=outroot,stdin=sp.PIPE,stdout=sp.PIPE,stderr=sp.PIPE,creationflags=flags|4)
    if not k.AssignProcessToJobObject(job,w.HANDLE(int(process._handle))):
        process.kill(); process.wait(); raise c.WinError(c.get_last_error())
    if resume(w.HANDLE(int(process._handle)))!=0: raise RuntimeError('resume failed')
    launched=time.perf_counter()
    timeout=False
    try: stdout,stderr=process.communicate(payload,timeout=deadline)
    except sp.TimeoutExpired:
        timeout=True
        # Contains only descendants launched by this isolated fixture.
        k.TerminateJobObject(job,1)
        stdout,stderr=process.communicate(timeout=5)
    return {'launched':True,'pid':process.pid,'launch_ms':round((launched-start)*1000,2),
            'elapsed_ms':round((time.perf_counter()-start)*1000,2),'timeout':timeout,
            'exit':process.returncode,'stdout_bytes':len(stdout),'stderr_bytes':len(stderr)}

try:
    setup=run([str(binary),'setup','codex','--plain'],0,None,60)
    (outroot/'setup-facts.json').write_text(json.dumps(setup),encoding='utf-8')
    hooks=json.loads((Path(env['CODEX_HOME'])/'hooks.json').read_text(encoding='utf-8'))
    declarations=hooks['hooks']
    command=declarations['UserPromptSubmit'][0]['hooks'][0]['commandWindows']
    (outroot/'declaration.json').write_text(json.dumps({'commandWindows':command,'timeout':declarations['UserPromptSubmit'][0]['hooks'][0]['timeout']}),encoding='utf-8')
    samples=int(os.environ.get('TB_CONSOLE_FIXTURE_SAMPLES','4'))
    cold_samples=int(os.environ.get('TB_CONSOLE_FIXTURE_COLD_SAMPLES','0'))
    concurrency=int(os.environ.get('TB_CONSOLE_FIXTURE_CONCURRENCY','0'))
    if not 1<=samples<=200 or not 0<=cold_samples<=50 or not 0<=concurrency<=4:
        raise ValueError('Fixture sample bounds exceeded')
    # Strict paired control: same command, exact environment/stdin, timing path
    # and initial appdata bytes. Preserve each run's state as evidence, restore
    # a pristine copy at the SAME absolute path, then change only creation flags.
    state=Path(env['LOCALAPPDATA'])
    pristine=outroot/'paired-pristine-appdata'
    shutil.copytree(state,pristine)
    paired=[]
    marker=outroot/'paired-timing.txt'
    env['TABBEACON_HOOK_TIMING_FILE']=str(marker)
    control_payload=json.dumps({'hook_event_name':'UserPromptSubmit','session_id':'fixture-paired-session','turn_id':'fixture-paired-turn','cwd':str(outroot)}).encode()
    control_env_sha256=hashlib.sha256(json.dumps(env,sort_keys=True).encode()).hexdigest()
    for label,flags in [('A_old_console',0),('B_01592_no_console',0x08000000)]:
        facts=run(invocation(command),flags,control_payload)
        facts.update(mode=label,timing=marker.read_text().strip() if marker.exists() else None,
            environment_sha256=control_env_sha256,stdin_sha256=hashlib.sha256(control_payload).hexdigest())
        if marker.exists(): marker.rename(outroot/(label+'-paired-timing.txt'))
        end=declarations['SessionEnd'][0]['hooks'][0]['commandWindows']
        endpayload=json.dumps({'hook_event_name':'SessionEnd','session_id':'fixture-paired-session','cwd':str(outroot)}).encode()
        facts['session_end']=run(invocation(end),flags,endpayload,5)
        if marker.exists(): marker.rename(outroot/(label+'-paired-end-timing.txt'))
        paired.append(facts)
        k.TerminateJobObject(job,0)
        archive=outroot/(label+'-paired-appdata')
        # Verify both resolved targets before the owned directory move. This
        # preserves evidence and never deletes a worktree/source/evidence root.
        if not state.resolve().is_relative_to(outroot) or not archive.resolve().is_relative_to(outroot):
            raise RuntimeError('owned fixture state escaped artifact root')
        if archive.exists(): raise RuntimeError('paired state archive already exists')
        state.rename(archive)
        shutil.copytree(pristine,state)
    for label,flags in [('A_old_console',0),('B_01592_no_console',0x08000000)]:
        metric=outroot/(label+'-console.json')
        run([sys.executable,__file__,'--inspect',str(metric)],flags,None,5)
        console=json.loads(metric.read_text())
        for sample in range(cold_samples+samples):
            # Fresh install state and first-session anchoring, with the actual
            # setup precondition (verified immutable runtime image) established
            # outside the Hook SLA, exactly as production setup does. Earlier
            # unprewarmed-state stress receipts are retained separately.
            cold_setup=None
            if sample<cold_samples:
                appdata=outroot/(label+f'-cold-{sample}-appdata');appdata.mkdir()
                codex_home=outroot/(label+f'-cold-{sample}-codex-home');codex_home.mkdir()
                env['LOCALAPPDATA']=str(appdata)
                env['CODEX_HOME']=str(codex_home)
                cold_setup=run([str(binary),'setup','codex','--plain'],0,None,60)
                if cold_setup['timeout'] or cold_setup['exit']!=0:
                    raise RuntimeError('cold install precondition failed')
            else:
                env['LOCALAPPDATA']=str(outroot/'appdata')
                env['CODEX_HOME']=str(outroot/'codex-home')
            marker=outroot/(label+f'-{sample}-timing.txt')
            env['TABBEACON_HOOK_TIMING_FILE']=str(marker)
            session='fixture-session' if os.getenv('TB_OWNED_NATIVE_PARENT') else label+str(sample)
            payload=json.dumps({'hook_event_name':'UserPromptSubmit','session_id':session,'turn_id':label+str(sample),'cwd':str(outroot)}).encode()
            facts=run(invocation(command),flags,payload)
            facts.update(mode=label,sample=sample,cold_state=sample<cold_samples,console=console,hook_ingress_reached=marker.exists(),
                         cold_setup=cold_setup,
                         timing=marker.read_text().strip() if marker.exists() else None)
            results.append(facts)
            if sample==cold_samples+samples-1:
                facts['lifecycle']=[]
                for event in ['PreToolUse','PostToolUse','Stop']:
                    event_marker=outroot/(label+'-'+event+'-timing.txt')
                    env['TABBEACON_HOOK_TIMING_FILE']=str(event_marker)
                    event_command=declarations[event][0]['hooks'][0]['commandWindows']
                    data=json.dumps({'hook_event_name':event,'session_id':session,'turn_id':label+str(sample),'cwd':str(outroot),'tool_name':'fixture-no-content'}).encode()
                    event_facts=run(invocation(event_command),flags,data)
                    event_facts.update(event=event,timing=event_marker.read_text().strip() if event_marker.exists() else None)
                    facts['lifecycle'].append(event_facts)
            # Exact generated SessionEnd command, no content, isolated state.
            end=declarations['SessionEnd'][0]['hooks'][0]['commandWindows']
            env['TABBEACON_HOOK_TIMING_FILE']=str(outroot/(label+f'-{sample}-end-timing.txt'))
            endpayload=json.dumps({'hook_event_name':'SessionEnd','session_id':session,'cwd':str(outroot)}).encode()
            facts['session_end']=run(invocation(end),flags,endpayload,5)
        if concurrency:
            # Different turns in one session/terminal: exercise the production
            # ownership locks and generation gate without global state writes.
            # Fixed environment is not changed while these calls run.
            env['LOCALAPPDATA']=str(outroot/'appdata')
            timing_directory=outroot/(label+'-concurrent-timing');timing_directory.mkdir()
            env.pop('TABBEACON_HOOK_TIMING_FILE',None)
            env['TABBEACON_HOOK_TIMING_DIRECTORY']=str(timing_directory)
            def concurrent_call(index):
                data=json.dumps({'hook_event_name':'UserPromptSubmit','session_id':session,'turn_id':label+f'-concurrent-{index}','cwd':str(outroot)}).encode()
                return run(invocation(command),flags,data)
            with ThreadPoolExecutor(max_workers=concurrency) as executor:
                concurrent=list(executor.map(concurrent_call,range(concurrency)))
            env.pop('TABBEACON_HOOK_TIMING_DIRECTORY',None)
            results.append({'mode':label,'concurrency':concurrency,'calls':concurrent,
                            'timing':[p.read_text().strip() for p in sorted(timing_directory.glob('*.txt'))]})
            env['TABBEACON_HOOK_TIMING_FILE']=str(outroot/(label+'-concurrent-end.txt'))
            run(invocation(end),flags,endpayload,5)
    leases=[json.loads(path.read_text()) for path in outroot.rglob('lease-*.json')]
    active_leases=sum(bool(lease.get('active')) for lease in leases)
    (outroot/'receipt.json').write_text(json.dumps({'binary_sha256':hashlib.sha256(binary.read_bytes()).hexdigest(),
        'private_console':True,'shell':shell,'command':'actual generated commandWindows',
        'stdio':'three redirected pipes; concurrent input/output with EOF deadline',
        'environment':'same isolated allowlisted session snapshot for A/B; no credentials or probe seam',
        'job':'suspend -> assign -> resume; exact-owned tree cleanup',
        'native_parent_fixture':bool(os.getenv('TB_OWNED_NATIVE_PARENT')),
        'native_parent_attribution':'actual installed Codex stdio-only test ancestor; NOT real provider Hook delivery',
        'terminal_content_scraped':False,'active_leases_after_session_end':active_leases,
        'owned_cleanup':'SessionEnd first; final exact-owned JobObject termination/close in finally',
        'paired_control':paired,
        'results':results},indent=2),encoding='utf-8')
except Exception as error:
    # Content-minimal fixture failures, never raw protocol stdout or payload.
    (outroot/'fixture-failure.json').write_text(json.dumps({'exception_class':type(error).__name__,
        'phase':'fixture execution/setup/owned cleanup','owned_cleanup':'exact JobObject finally'}))
    raise
finally:
    k.TerminateJobObject(job,0); k.CloseHandle(job); k.FreeConsole()
