//! Per-terminal color authority shared by the one-shot provider writers.
//! Callers retain their existing provider route/lease locks while using this
//! bounded lock. A write intent revokes the previous owner's reset authority
//! before terminal I/O; only a confirmed flush can acquire new authority.

use std::{
    fs::{self, File, OpenOptions},
    io::{self, Read, Write},
    path::{Path, PathBuf},
    time::Duration,
};

use atomic_write_file::AtomicWriteFile;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::lock_budget::try_lock_file_with_budget;

const SCHEMA: &str = "tabbeacon-terminal-color-v1";
const MAX_RECORD_BYTES: u64 = 512;
const MAX_TERMINAL_FILES: usize = 1_024;
const LOCK_BUDGET: Duration = Duration::from_millis(100);

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Record {
    schema: String,
    terminal_sha256: String,
    state: ColorState,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case", tag = "kind")]
enum ColorState {
    Unowned,
    Unknown,
    Owned {
        provider: String,
        session_sha256: String,
    },
}

impl Record {
    fn new(terminal: &str) -> Self {
        Self {
            schema: SCHEMA.to_owned(),
            terminal_sha256: terminal.to_owned(),
            state: ColorState::Unowned,
        }
    }

    fn valid(&self, terminal: &str) -> bool {
        self.schema == SCHEMA
            && self.terminal_sha256 == terminal
            && match &self.state {
                ColorState::Unowned | ColorState::Unknown => true,
                ColorState::Owned {
                    provider,
                    session_sha256,
                } => matches!(provider.as_str(), "codex" | "cursor") && is_digest(session_sha256),
            }
    }
}

fn is_digest(value: &str) -> bool {
    value.len() == 64
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

pub(crate) fn binding_from_identity(identity: &str) -> String {
    let mut digest = Sha256::new();
    digest.update(identity.len().to_le_bytes());
    digest.update(identity.as_bytes());
    format!("{:x}", digest.finalize())
}

/// Removes only the final frame-color OSC generated by our typed renderer.
/// Title and progress bytes remain untouched. The caller never passes Hook
/// input or terminal output through this function.
pub(crate) fn without_generated_color(bytes: &[u8]) -> &[u8] {
    const RESET: &[u8] = b"\x1b]104;264\x1b\\";
    const SET: &[u8] = b"\x1b]4;264;rgb:";
    if bytes.ends_with(RESET) {
        return &bytes[..bytes.len() - RESET.len()];
    }
    let suffix_len = SET.len() + 8 + 2;
    if bytes.len() < suffix_len {
        return bytes;
    }
    let suffix = &bytes[bytes.len() - suffix_len..];
    let rgb = &suffix[SET.len()..suffix_len - 2];
    if suffix.starts_with(SET)
        && suffix.ends_with(b"\x1b\\")
        && rgb.len() == 8
        && rgb[2] == b'/'
        && rgb[5] == b'/'
        && rgb
            .iter()
            .enumerate()
            .all(|(index, byte)| index == 2 || index == 5 || byte.is_ascii_hexdigit())
    {
        &bytes[..bytes.len() - suffix_len]
    } else {
        bytes
    }
}

fn reject_link(path: &Path) -> io::Result<()> {
    match fs::symlink_metadata(path) {
        Ok(metadata) => {
            #[cfg(windows)]
            {
                use std::os::windows::fs::MetadataExt;
                if metadata.file_attributes() & 0x400 != 0 {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidInput,
                        "terminal color path is a reparse point",
                    ));
                }
            }
            if metadata.file_type().is_symlink() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "terminal color path is a link",
                ));
            }
            Ok(())
        }
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error),
    }
}

fn ensure_record_capacity(path: &Path, maximum_entries: usize) -> io::Result<()> {
    let directory = path
        .parent()
        .ok_or_else(|| io::Error::other("terminal color directory unavailable"))?;
    let mut count = 0;
    for entry in fs::read_dir(directory)?.take(maximum_entries + 2) {
        entry?;
        count += 1;
    }
    if count > maximum_entries {
        Err(io::Error::other("terminal color record capacity reached"))
    } else {
        Ok(())
    }
}

pub(crate) struct TerminalColorStore {
    directory: PathBuf,
    terminal: String,
}

impl TerminalColorStore {
    pub(crate) fn new(state_root: &Path, terminal: &str) -> io::Result<Self> {
        if !is_digest(terminal) {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "invalid terminal color binding",
            ));
        }
        reject_link(state_root)?;
        let directory = state_root.join("terminal-color-v1");
        reject_link(&directory)?;
        Ok(Self {
            directory,
            terminal: terminal.to_owned(),
        })
    }

    pub(crate) fn with_lock<T>(
        &self,
        action: impl FnOnce(&mut LockedColor<'_>) -> io::Result<T>,
    ) -> io::Result<T> {
        reject_link(&self.directory)?;
        fs::create_dir_all(&self.directory)?;
        reject_link(&self.directory)?;
        let lock_path = self.directory.join("color.lock");
        reject_link(&lock_path)?;
        let lock = OpenOptions::new()
            .read(true)
            .write(true)
            .create(true)
            .truncate(false)
            .open(lock_path)?;
        try_lock_file_with_budget(&lock, LOCK_BUDGET)?;
        let path = self.directory.join(format!("color-{}.json", self.terminal));
        let record = self.load(&path)?;
        let result = action(&mut LockedColor {
            path: &path,
            record,
        });
        // Closing this owned lock cannot turn an already flushed color into a
        // reported pre-output failure solely due to a separate unlock error.
        drop(lock);
        result
    }

    fn load(&self, path: &Path) -> io::Result<Record> {
        reject_link(path)?;
        let file = match File::open(path) {
            Ok(file) => file,
            Err(error) if error.kind() == io::ErrorKind::NotFound => {
                return Ok(Record::new(&self.terminal));
            }
            Err(error) => return Err(error),
        };
        let mut bytes = Vec::new();
        file.take(MAX_RECORD_BYTES + 1).read_to_end(&mut bytes)?;
        if bytes.len() as u64 > MAX_RECORD_BYTES {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "terminal color record oversized",
            ));
        }
        let record: Record = serde_json::from_slice(&bytes).map_err(|_| {
            io::Error::new(io::ErrorKind::InvalidData, "invalid terminal color record")
        })?;
        if !record.valid(&self.terminal) {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "terminal color record drift",
            ));
        }
        Ok(record)
    }
}

pub(crate) struct LockedColor<'a> {
    path: &'a Path,
    record: Record,
}

impl LockedColor<'_> {
    fn save(&mut self, state: ColorState) -> io::Result<()> {
        self.record.state = state;
        reject_link(self.path)?;
        let missing = match fs::symlink_metadata(self.path) {
            Ok(_) => false,
            Err(error) if error.kind() == io::ErrorKind::NotFound => true,
            Err(error) => return Err(error),
        };
        if missing {
            // No automatic deletion of an unknown terminal's record. A full
            // store stops decoration instead of growing without a bound.
            ensure_record_capacity(self.path, MAX_TERMINAL_FILES)?;
        }
        let bytes = serde_json::to_vec(&self.record).map_err(io::Error::other)?;
        let mut file = AtomicWriteFile::options().open(self.path)?;
        file.write_all(&bytes)?;
        file.flush()?;
        file.commit()
    }

    pub(crate) fn begin_write(&mut self) -> io::Result<()> {
        self.save(ColorState::Unknown)
    }

    pub(crate) fn confirm_write(&mut self, provider: &str, session: &str) -> io::Result<()> {
        if !matches!(provider, "codex" | "cursor") || !is_digest(session) {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "invalid terminal color owner",
            ));
        }
        self.save(ColorState::Owned {
            provider: provider.to_owned(),
            session_sha256: session.to_owned(),
        })
    }

    /// Revokes the exact owner before a reset. A missing legacy record is not
    /// proof of ownership and must never authorize a reset.
    pub(crate) fn revoke_if_owned(&mut self, provider: &str, session: &str) -> io::Result<bool> {
        if self.record.state
            == (ColorState::Owned {
                provider: provider.to_owned(),
                session_sha256: session.to_owned(),
            })
        {
            self.save(ColorState::Unowned)?;
            Ok(true)
        } else {
            Ok(false)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unknown_flush_and_other_terminal_never_authorize_foreign_reset() {
        let root = tempfile::tempdir().unwrap();
        let first = TerminalColorStore::new(root.path(), &"a".repeat(64)).unwrap();
        let second = TerminalColorStore::new(root.path(), &"b".repeat(64)).unwrap();
        let cursor = "c".repeat(64);
        let codex = "d".repeat(64);
        first
            .with_lock(|record| {
                record.begin_write()?;
                record.confirm_write("cursor", &cursor)
            })
            .unwrap();
        second
            .with_lock(|record| {
                assert!(!record.revoke_if_owned("cursor", &cursor)?);
                record.begin_write()?;
                record.confirm_write("codex", &codex)
            })
            .unwrap();
        first
            .with_lock(|record| {
                record.begin_write()?; // interruption before flush confirmation
                assert!(!record.revoke_if_owned("cursor", &cursor)?);
                assert!(!record.revoke_if_owned("codex", &codex)?);
                Ok(())
            })
            .unwrap();
        second
            .with_lock(|record| {
                assert!(record.revoke_if_owned("codex", &codex)?);
                assert!(!record.revoke_if_owned("codex", &codex)?);
                Ok(())
            })
            .unwrap();
    }

    #[test]
    fn strips_only_our_generated_trailing_color_sequence() {
        let prefix = b"\x1b]0;owned-title\x1b\\\x1b]9;4;0;0\x1b\\";
        let mut set = prefix.to_vec();
        set.extend_from_slice(b"\x1b]4;264;rgb:11/22/33\x1b\\");
        assert_eq!(without_generated_color(&set), prefix);
        let mut reset = prefix.to_vec();
        reset.extend_from_slice(b"\x1b]104;264\x1b\\");
        assert_eq!(without_generated_color(&reset), prefix);
        assert_eq!(without_generated_color(prefix), prefix);
        let wrong = b"\x1b]4;265;rgb:11/22/33\x1b\\";
        assert_eq!(without_generated_color(wrong), wrong);
    }

    #[test]
    #[allow(clippy::redundant_closure_for_method_calls)] // The method pointer is not lifetime-general enough for with_lock.
    fn malformed_record_blocks_transition_without_reset_or_replacement() {
        let root = tempfile::tempdir().unwrap();
        let terminal = "a".repeat(64);
        let store = TerminalColorStore::new(root.path(), &terminal).unwrap();
        store.with_lock(|record| record.begin_write()).unwrap();
        let path = root
            .path()
            .join("terminal-color-v1")
            .join(format!("color-{terminal}.json"));
        fs::write(&path, b"not-json").unwrap();
        assert_eq!(
            store
                .with_lock(|record| record.revoke_if_owned("cursor", &"c".repeat(64)))
                .unwrap_err()
                .kind(),
            io::ErrorKind::InvalidData
        );
        assert_eq!(fs::read(&path).unwrap(), b"not-json");
    }

    #[test]
    fn new_terminal_capacity_refuses_growth_and_preserves_existing_records() {
        let root = tempfile::tempdir().unwrap();
        let directory = root.path().join("terminal-color-v1");
        fs::create_dir(&directory).unwrap();
        for name in ["color-a.json", "color-b.json", "color-c.json"] {
            fs::write(directory.join(name), b"retained").unwrap();
        }
        let new_path = directory.join("color-d.json");
        assert!(ensure_record_capacity(&new_path, 2).is_err());
        assert!(!new_path.exists());
        for name in ["color-a.json", "color-b.json", "color-c.json"] {
            assert_eq!(fs::read(directory.join(name)).unwrap(), b"retained");
        }
    }

    #[test]
    fn held_color_lock_refuses_a_competing_write_without_output() {
        use std::{sync::mpsc, thread};

        let root = tempfile::tempdir().unwrap();
        let terminal = "a".repeat(64);
        let holder_store = TerminalColorStore::new(root.path(), &terminal).unwrap();
        let contender_store = TerminalColorStore::new(root.path(), &terminal).unwrap();
        let cursor = "c".repeat(64);
        let (entered_tx, entered_rx) = mpsc::channel();
        let (release_tx, release_rx) = mpsc::channel();
        let holder = thread::spawn(move || {
            holder_store.with_lock(|record| {
                record.begin_write()?;
                entered_tx.send(()).unwrap();
                release_rx.recv_timeout(Duration::from_secs(2)).unwrap();
                record.confirm_write("cursor", &cursor)
            })
        });
        entered_rx.recv_timeout(Duration::from_secs(2)).unwrap();
        let mut bytes = Vec::new();
        let refused = contender_store.with_lock(|record| {
            record.begin_write()?;
            bytes.extend_from_slice(b"would-write-color");
            Ok(())
        });
        assert_eq!(refused.unwrap_err().kind(), io::ErrorKind::WouldBlock);
        assert!(bytes.is_empty());
        release_tx.send(()).unwrap();
        holder.join().unwrap().unwrap();
        contender_store
            .with_lock(|record| {
                assert!(record.revoke_if_owned("cursor", &"c".repeat(64))?);
                Ok(())
            })
            .unwrap();
    }
}
